name: graph_webspark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
